### ISSUE TITLE
Installer is blocked

### ISSUE THREAD

**Issue by SeanFeldman** [Carael/CrossBusExplorer#15]
Running as an administrator, getting the following error when trying to install:

> This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)

![image](https://user-images.githubusercontent.com/1309622/204973393-4bf79c8e-4de4-439a-83ce-53d7507f7dc5.png)

**Comment by Carael** [comment]
@SeanFeldman The only way to publish from Maui is to create MSIX which needs to be signed with certificate. At the moment I'm signing with self signed certificate which needs to be manually added to the Trusted Root Certificate store.

View properties of the installer -> Digital Signatures -> Details of the Certificate -> View Certificate -> Install to local thrusted certificate store.

Don't wanted to invest in the certificate since I'm still not sure if the app would stay with Maui or I use Electron as a host.

**Comment by SeanFeldman** [comment]
I ran it locally w/o going through the installer.
You might want to add instructions to the README.md on how to use the installer or run the solution to avoid installation.

**Comment by Carael** [comment]
Great! I've added the instructions to README.md of this problem. I have on my pipeline to add Nuke build script and document it.

**Comment by Carael** [comment]
@SeanFeldman Just a quick update. The installer doesn't require a certificate of windows now. It's classic installer bundled with Electron.

**Comment by SeanFeldman** [comment]
Yeah, I tried it yesterday 👍
